apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Namespace }}-storage
  namespace: {{ .Release.Namespace }}
  labels:
    identifier: storage
spec:
  accessModes:
  - ReadWriteMany      
  resources:
     requests:
       storage: {{ .Values.volumeSize }}
  selector: 
    matchLabels: 
      identifier: storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Namespace }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    identifier: db
spec:
  accessModes:
  - ReadWriteMany      
  resources:
     requests:
       storage: {{ .Values.DBSize }}
  selector: 
    matchLabels: 
      identifier: db
