apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-unms"
  labels:
    {{- include "unms.labels" . | nindent 4 }}
type: Opaque
data:
  unms-token: {{ include "unms.token" . | b64enc | quote }}
  unms-version: {{ include "unms.version" . | b64enc | quote }}
