apiVersion: v1
kind: Service
metadata:
  name: {{ include "unms.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unms.labels" . | nindent 4 }}
    component: unms
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  clusterIP: None
  ports:
  - port: 8081
    name: http
  - port: 8082
    name: ws
  selector:
    {{- include "unms.selectorLabels" . | nindent 8 }}
