apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.podName }}
spec:
  clusterIP: None
  ports:
  - port: 443
    name: https
  selector:
    k8s-app: {{ .Values.podName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.podName }}-db
spec:
  clusterIP: None
  ports:
  - port: 5432
    name: postgresql
  selector:
    k8s-app: {{ .Values.podName }}-db
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.podName }}-redis
spec:
  clusterIP: None
  ports:
  - port: 6379
    name: redis
  selector:
    k8s-app: {{ .Values.podName }}-redis

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.podName }}-rbmq
spec:
  clusterIP: None
  ports:
  - port: 5672
    name: rbmq
  selector:
    k8s-app: {{ .Values.podName }}-rbmq
