---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "unms.fullname" . }}
  labels:
    {{- include "unms.labels" . | nindent 4 }}
    component: unms
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  serviceName: {{ include "unms.fullname" . }}
  selector:
    matchLabels:
      {{- include "unms.selectorLabels" . | nindent 6 }}
      component: unms
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  updateStrategy:
    type: {{ .Values.updateStrategy }}
  template:
    metadata:
      name: {{ include "unms.fullname" . }}
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      labels:
        {{- include "unms.selectorLabels" . | nindent 8 }}
        component: unms
        {{- range $key, $value := .Values.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      containers:
      - image: {{ .Values.image }}:{{ .Values.imageTag }}
        name: "{{ template "unms.fullname" . }}"
        imagePullPolicy: Always
        env:
        - name: UCRM_HOST
          value: "{{ .Release.Name }}-ucrm"
        - name: UCRM_PORT
          value: "80"
        - name: UNMS_NGINX_HOST
          value: "{{ .Release.Name }}-unms-nginx"
        - name: UNMS_NGINX_PORT
          value: "12345"
        - name: UNMS_PG_HOST
          value: "{{ .Release.Name }}-postgresql"
        - name: UNMS_PG_PORT
          value: "5432"
        - name: UNMS_RABBITMQ_HOST
          value: "{{ .Release.Name }}-rabbitmq"
        - name: UNMS_RABBITMQ_PORT
          value: "5672"
        - name: UNMS_REDISDB_HOST
          value: "{{ .Release.Name }}-redis-master"
        - name: UNMS_REDISDB_PORT
          value: "6379"
        - name: UNMS_SIRIDB_HOST
          value: "{{ .Release.Name }}-siridb"
        - name: UNMS_SIRIDB_PORT
          value: "9000"
        - name: UNMS_SIRIDB_PORT
          value: "9000"
        - name: NODE_ENV
          value: "production"
        - name: HTTP_PORT
          value: "8081"
        - name: WS_PORT
          value: "8082"
        - name: WS_SHELL_PORT
          value: "8083"
        - name: UNMS_WS_API_PORT
          value: "8084"
        - name: UNMS_NETFLOW_PORT
          value: "2055"
        - name: PUBLIC_HTTPS_PORT
          value: "443"
        - name: PUBLIC_WS_PORT
          value: "443"
        - name: NGINX_HTTPS_PORT
          value: "443"
        - name: NGINX_WS_PORT
          value: "443"
        - name: SUSPEND_PORT
          value: "81"
        - name: BRANCH
          value: "master"
        - name: SECURE_LINK_SECRET
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-unms"
              key: unms-token
        - name: UNMS_TOKEN
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-unms"
              key: unms-token
        - name: CLUSTER_SIZE
          value: "auto"
        - name: UNMS_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-postgresql"
              key: postgresql-password
        - name: UNMS_PG_USER
          value: "unms"
        - name: UNMS_PG_DB
          value: "unms"
        - name: UNMS_PG_SCHEMA
          value: "unms"
        - name: USE_LOCAL_DISCOVERY
          value: "true"
        - name: UNMS_USER_ID
          value: "{{ .Values.unmsUserId }}"
        {{- if .Values.persistence.enabled }}
        volumeMounts:
        - name: "storage"
          mountPath: /home/app/unms/data
        {{- end }}
        resources:
          {{ toYaml .Values.resources | indent 10 }}
      {{- if .Values.persistence.enabled }}
      initContainers:
        - name: init
          image: busybox:1.32
          imagePullPolicy: IfNotPresent
          command:
            - 'sh'
            - '-c'
            - 'mkdir -p -m 777 /data/config-backups; mkdir -p -m 777 /data/unms-backups; mkdir -p -m 777 /data/import'
          volumeMounts:
          - name: "storage"
            mountPath: /data
      {{- end }}
      {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: "storage"
      labels:
        {{- include "unms.labels" . | nindent 8 }}
        {{- include "unms.selectorLabels" . | nindent 8 }}
    spec:
      accessModes:
      {{- range .Values.persistence.accessModes }}
        - {{ . | quote }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
      {{ if .Values.persistence.existingClaim }}
      selector:
        matchLabels:
          name: {{ .Values.persistence.existingClaim | quote }}
      {{- else }}
        {{- if .Values.persistence.storageClass }}
      storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end }}
      {{- end }}
  {{- end }}
