apiVersion: v1
kind: Service
metadata:
  name: {{ include "unms-nginx.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unms-nginx.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    name: http
  - port: 81
    name: suspend
  - port: 443
    name: https
  selector:
    {{- include "unms-nginx.selectorLabels" . | nindent 8 }}
