podName: unms

image: ubnt/unms
tag: 0.10.4

rbmqImage: rabbitmq:latest
DBimage: postgres:latest
redisImage: redis:latest

replicas: 1
vhost: unms.domain.tld
clusterDomain: cluster.local

volumeSize: 2Gi
DBSize: 10Gi

postgresDBuser: unms
postgresDBname: unms
postgresDBpassword: PassWord
