apiVersion: v1
kind: Service
metadata:
  name: {{ include "siridb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "siridb.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 9000
    name: client
  - port: 9010
    name: backend
  selector:
    {{- include "siridb.selectorLabels" . | nindent 8 }}
