---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "siridb.fullname" . }}
  labels:
    {{- include "siridb.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  serviceName: {{ include "siridb.fullname" . }}
  selector:
    matchLabels:
      {{- include "siridb.selectorLabels" . | nindent 6 }}
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  updateStrategy:
    type: {{ .Values.updateStrategy }}
  template:
    metadata:
      name: {{ include "siridb.fullname" . }}
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      labels:
        {{- include "siridb.selectorLabels" . | nindent 8 }}
        {{- range $key, $value := .Values.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: "{{ template "siridb.fullname" . }}"
        env: []
        {{- if .Values.persistence.enabled }}
        volumeMounts:
        - name: "storage"
          mountPath: /var/lib/siridb
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
      {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: "storage"
      labels:
        app.kubernetes.io/name: "storage"
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      accessModes:
      {{- range .Values.persistence.accessModes }}
        - {{ . | quote }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
      {{ if .Values.persistence.existingClaim }}
      selector:
        matchLabels:
          name: {{ .Values.persistence.existingClaim | quote }}
      {{- else }}
        {{- if .Values.persistence.storageClass }}
      storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end }}
      {{- end }}
  {{- end }}
